apiVersion: v1
kind: Service
metadata:
  name: goudot-srv
  namespace: goudot-ns
spec:
  selector:
    app: goudot-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080  # Port entre 30000-32767
    protocol: TCP
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10  # 